export const StatusProgressTheme = {
	baseStyle: {
		margin: "auto",
		padding: "20px",
		minWidth: "700px",
		fontWeight: "bold",
		color: "grey.400",
		div: {
			display: "inline-block",
			position: "relative",
			height: "25px",
			lineHeight: "25px",
			padding: "0 20px",
			border: "1px solid #ccc",
			marginRight: "2px",
			backgroundColor: "white",
			cursor: "pointer",
		},
		"div.right:after": {
			content: "''",
			borderTop: "1px solid #ccc",
			borderRight: "1px solid #ccc",
			width: "18px",
			height: "18px",
			position: "absolute",
			right: "0",
			top: "-1px",
			backgroundColor: "white",
			zIndex: 150,
			transform: "translate(10px,4px) rotate(45deg)",
		},
		"div.left:before": {
			content: "''",
			borderTop: "1px solid #ccc",
			borderRight: "1px solid #ccc",
			width: "18px",
			height: "18px",
			position: "absolute",
			left: "0",
			top: "-1px",
			backgroundColor: "white",
			zIndex: 50,
			transform: "translate(-10px,4px) rotate(45deg)",
		},
		".active": { backgroundColor: "blue", color: "white", cursor: "default" },
		"div.active:after": { backgroundColor: "blue" },
	},
};
